language: c

sudo: true
dist:  bionic

addons:
  apt:
    sources:
      - sourceline: 'ppa:dosemu2/ppa'
      - sourceline: 'ppa:jwt27/djgpp-toolchain'
      - sourceline: 'ppa:tkchia/build-ia16'
    packages:
      - comcom32
      - git
      - bash
      - autoconf
      - autotools-dev
      - automake
      - coreutils
      - linuxdoc-tools
      - bison
      - flex
      - gawk
      - sed
      - libbsd-dev
      - libx11-dev
      - libxext-dev
      - libslang2-dev
      - xfonts-utils
      - libgpm-dev
      - libasound2-dev
      - libsdl2-dev
      - libsdl1.2-dev
      - ladspa-sdk
      - libfluidsynth-dev
      - libao-dev
      - libvdeplug-dev
      - libreadline-dev
      - libjson-c-dev
      - binutils-dev
      - pkg-config
      - clang
      - nasm
      - libstdc++-5-dev
      - python3-pexpect
      - gcc-djgpp
      - qemu-system-common
      - gdb
      - valgrind
      - gcc-ia16-elf
      - dos2unix
    update: true

cache:
  directories:
    - $HOME/cache

env: FDPP_KERNEL_DIR="$(pwd)/localfdpp/share/fdpp"

jobs:
  include:
    - name: Minimal
      if: ((type = cron) OR \
           (type = pull_request) AND (commit_message =~ /\[with ci\]/))

before_install:
  - echo "before_install"

install:
  - ./travis_build.sh

before_script:
  - sudo setfacl -m u:${USER}:rw /dev/kvm

script:
  - ./travis_test.sh
