language: c

sudo: true
dist: focal

if: type = cron

cache:
  directories:
    - $HOME/cache

before_install:
  - ./ci_prereq.sh

install:
  - ./ci_build.sh

before_script:
# this acl no longer persists in Focal due to /dev/kvm management by systemd
# - sudo setfacl -m u:${USER}:rw /dev/kvm
# so we have to do this instead
  - sudo chmod 666 /dev/kvm

script:
  - ./ci_test.sh

after_script:
  - echo "after_script"
